name: Export AdventureWorks Tables to CSV

on:
  push:
    branches:
      - main

jobs:
  export-tables:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SQL Server
      uses: microsoft/setup-sqlserver@v1
      with:
        sqlVersion: '2019-latest'
    
    - name: Restore AdventureWorks Database
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ secrets.SA_PASSWORD }} -Q "RESTORE DATABASE AdventureWorks FROM DISK = '$(pwd)/AdventureWorks.bak' WITH MOVE 'AdventureWorks_Data' TO '/var/opt/mssql/data/AdventureWorks.mdf', MOVE 'AdventureWorks_Log' TO '/var/opt/mssql/data/AdventureWorks_log.ldf';"
      env:
        SA_PASSWORD: ${{ secrets.SA_PASSWORD }}

    - name: Export Tables to CSV
      run: |
        mkdir -p csv_exports
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ secrets.SA_PASSWORD }} -d AdventureWorks -Q "SET NOCOUNT ON; DECLARE @tablename AS NVARCHAR(500); DECLARE table_cursor CURSOR FOR SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'; OPEN table_cursor; FETCH NEXT FROM table_cursor INTO @tablename; WHILE @@FETCH_STATUS = 0 BEGIN DECLARE @sql AS NVARCHAR(1000); SET @sql = 'bcp AdventureWorks.' + @tablename + ' out csv_exports/' + @tablename + '.csv -c -t, -S localhost -U sa -P ' + '${{ secrets.SA_PASSWORD }}'; EXEC xp_cmdshell @sql; FETCH NEXT FROM table_cursor INTO @tablename; END; CLOSE table_cursor; DEALLOCATE table_cursor;"
      env:
        SA_PASSWORD: ${{ secrets.SA_PASSWORD }}

    - name: Upload CSV files
      uses: actions/upload-artifact@v2
      with:
        name: csv-exports
        path: csv_exports/
